import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import AuthenticatorSettings from './AuthenticatorSettings';
import {authenticatorAction,authenticatorStatus} from '../services/authenticatorService';
import {requestOtp,verifyOtp} from '../services/authService';
jest.mock('../api/demoAdapter',()=>({demoMode:false}));
jest.mock('../services/authenticatorService',()=>({authenticatorAction:jest.fn(),authenticatorStatus:jest.fn()}));
jest.mock('../services/authService',()=>({requestOtp:jest.fn(),verifyOtp:jest.fn()}));
beforeEach(()=>{jest.resetAllMocks();localStorage.clear();});
test('setup is private, explicit and requires code confirmation',async()=>{
  authenticatorStatus.mockResolvedValue({enabled:false});
  authenticatorAction.mockResolvedValueOnce({setupKey:'TESTONLYKEY',account:'a@example.com'}).mockResolvedValueOnce({enabled:true});
  render(<AuthenticatorSettings email="a@example.com"/>);
  expect(authenticatorStatus).not.toHaveBeenCalled();
  fireEvent.click(screen.getByText('Manage authenticator'));
  await screen.findByText('Status: Not enabled');
  fireEvent.change(screen.getByLabelText('Current account password'),{target:{value:'test-password'}});
  fireEvent.click(screen.getByText('Create setup key'));
  await screen.findByDisplayValue('TESTONLYKEY');
  expect(screen.getByText('Status: Not enabled')).toBeInTheDocument();
  expect(localStorage.length).toBe(0);
  fireEvent.change(screen.getByLabelText('Authenticator app code'),{target:{value:'123456'}});
  fireEvent.click(screen.getByText('Confirm and enable'));
  await screen.findByText('Status: Enabled');
  expect(screen.queryByDisplayValue('TESTONLYKEY')).not.toBeInTheDocument();
  expect(authenticatorAction).toHaveBeenLastCalledWith('confirm',{code:'123456'});
});
test('lost-phone recovery uses verified email token and current password',async()=>{
  authenticatorStatus.mockResolvedValue({enabled:true});requestOtp.mockResolvedValue({});
  verifyOtp.mockResolvedValue({otpToken:'email-proof'});authenticatorAction.mockResolvedValue({enabled:false});
  render(<AuthenticatorSettings email="a@example.com"/>);
  fireEvent.click(screen.getByText('Manage authenticator'));await screen.findByText('Status: Enabled');
  fireEvent.click(screen.getByText('Lost your phone? Send email recovery code'));
  await screen.findByLabelText('Email recovery code');
  fireEvent.change(screen.getByLabelText('Current account password'),{target:{value:'test-password'}});
  fireEvent.change(screen.getByLabelText('Email recovery code'),{target:{value:'654321'}});
  fireEvent.click(screen.getByText('Disable using password and email recovery'));
  await waitFor(()=>expect(authenticatorAction).toHaveBeenCalledWith('disable',{password:'test-password',emailOtpToken:'email-proof'}));
  await screen.findByText('Status: Not enabled');
});
